version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-nestjs
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dna
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  wait:
    image: waisbrot/wait
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - TARGETS=mysql:3306
